<scheme name="defdo latte" version="142" parent_scheme="Default">
  <meta>
    <property name="author" value="defdo"/>
  </meta>
  <colors>
    <option name="BACKGROUND" value="f7f2e9"/>
    <option name="CARET_COLOR" value="0e9bc0"/>
    <option name="CARET_ROW_COLOR" value="eae5dd"/>
    <option name="SELECTION_BACKGROUND" value="bdebf7"/>
    <option name="SELECTION_FOREGROUND" value=""/>
    <option name="GUTTER_BACKGROUND" value="f7f2e9"/>
    <option name="LINE_NUMBERS_COLOR" value="b4b1ac"/>
    <option name="FOLDING_LINES_COLOR" value="cecbc4"/>
    <option name="INDENT_GUIDE" value="cecbc4"/>
    <option name="SELECTED_INDENT_GUIDE" value="bdebf7"/>
    <option name="WHITESPACES" value="cecbc4"/>
    <option name="METHOD_SEPARATORS_COLOR" value="cecbc4"/>
    <option name="ADDED_LINES_COLOR" value="0a7a4f"/>
    <option name="MODIFIED_LINES_COLOR" value="9c7a02"/>
    <option name="DELETED_LINES_COLOR" value="b33a3a"/>
    <option name="TELEPATHY_COLOR" value="0b7a94"/>
    <option name="HYPERLINK_COLOR" value="0055b8"/>
    <option name="FOLLOWED_HYPERLINK_COLOR" value="3e7e9b"/>
  </colors>
  <attributes>
    <option name="TEXT">
      <value>
        <option name="FOREGROUND" value="16181d"/>
      </value>
    </option>
    <option name="FOLLOWED_HYPERLINK_ATTRIBUTES">
      <value>
        <option name="FOREGROUND" value="055b8"/><option name="FONT_TYPE" value="2"/>
      </value>
    </option>
    <option name="KEYWORD">
      <value>
        <option name="FOREGROUND" value="7a4fd0"/>
      </value>
    </option>
    <option name="CONTROL_FLOW_KEYWORD">
      <value>
        <option name="FOREGROUND" value="7a4fd0"/><option name="FONT_TYPE" value="1"/>
      </value>
    </option>
    <option name="STRING">
      <value>
        <option name="FOREGROUND" value="0a7a4f"/>
      </value>
    </option>
    <option name="CHARACTER">
      <value>
        <option name="FOREGROUND" value="0a7a4f"/>
      </value>
    </option>
    <option name="ESCAPE_CHARACTER">
      <value>
        <option name="FOREGROUND" value="b3541e"/>
      </value>
    </option>
    <option name="NUMBER">
      <value>
        <option name="FOREGROUND" value="b3541e"/>
      </value>
    </option>
    <option name="CONSTANT">
      <value>
        <option name="FOREGROUND" value="b3541e"/>
      </value>
    </option>
    <option name="STATIC_FINAL_FIELD">
      <value>
        <option name="FOREGROUND" value="b3541e"/>
      </value>
    </option>
    <option name="FUNCTION_DECLARATION">
      <value>
        <option name="FOREGROUND" value="0055b8"/>
      </value>
    </option>
    <option name="FUNCTION_CALL">
      <value>
        <option name="FOREGROUND" value="0055b8"/>
      </value>
    </option>
    <option name="GLOBAL_FUNCTION">
      <value>
        <option name="FOREGROUND" value="0055b8"/>
      </value>
    </option>
    <option name="CLASS_NAME">
      <value>
        <option name="FOREGROUND" value="9c7a02"/>
      </value>
    </option>
    <option name="INTERFACE_NAME">
      <value>
        <option name="FOREGROUND" value="9c7a02"/>
      </value>
    </option>
    <option name="ABSTRACT_CLASS_NAME_ATTRIBUTES">
      <value>
        <option name="FOREGROUND" value="9c7a02"/><option name="FONT_TYPE" value="2"/>
      </value>
    </option>
    <option name="ANNOTATION_NAME_ATTRIBUTES">
      <value>
        <option name="FOREGROUND" value="9c7a02"/><option name="FONT_TYPE" value="2"/>
      </value>
    </option>
    <option name="DOC_COMMENT">
      <value>
        <option name="FOREGROUND" value="6b7a80"/><option name="FONT_TYPE" value="2"/>
      </value>
    </option>
    <option name="COMMENT">
      <value>
        <option name="FOREGROUND" value="6b7a80"/><option name="FONT_TYPE" value="2"/>
      </value>
    </option>
    <option name="BLOCK_COMMENT">
      <value>
        <option name="FOREGROUND" value="6b7a80"/><option name="FONT_TYPE" value="2"/>
      </value>
    </option>
    <option name="LINE_COMMENT">
      <value>
        <option name="FOREGROUND" value="6b7a80"/><option name="FONT_TYPE" value="2"/>
      </value>
    </option>
    <option name="OPERATOR">
      <value>
        <option name="FOREGROUND" value="3e7e9b"/>
      </value>
    </option>
    <option name="PARENTHETS">
      <value>
        <option name="FOREGROUND" value="3e7e9b"/>
      </value>
    </option>
    <option name="BRACKETS">
      <value>
        <option name="FOREGROUND" value="3e7e9b"/>
      </value>
    </option>
    <option name="BRACES">
      <value>
        <option name="FOREGROUND" value="3e7e9b"/>
      </value>
    </option>
    <option name="COMMA">
      <value>
        <option name="FOREGROUND" value="3e7e9b"/>
      </value>
    </option>
    <option name="SEMICOLON">
      <value>
        <option name="FOREGROUND" value="3e7e9b"/>
      </value>
    </option>
    <option name="DOT">
      <value>
        <option name="FOREGROUND" value="3e7e9b"/>
      </value>
    </option>
    <option name="GLOBAL_VARIABLE">
      <value>
        <option name="FOREGROUND" value="16181d"/>
      </value>
    </option>
    <option name="LOCAL_VARIABLE">
      <value>
        <option name="FOREGROUND" value="16181d"/>
      </value>
    </option>
    <option name="PARAMETER">
      <value>
        <option name="FOREGROUND" value="16181d"/>
      </value>
    </option>
    <option name="TAG_NAME">
      <value>
        <option name="FOREGROUND" value="d3405a"/>
      </value>
    </option>
    <option name="ATTRIBUTE_NAME">
      <value>
        <option name="FOREGROUND" value="9c7a02"/>
      </value>
    </option>
  </attributes>
</scheme>
